// Veridian Markets — data export tool.
// Reads the mock "database" (the data .jsx files) and writes flat tables you can
// open as columns in VS Code: CSV (best with the Rainbow CSV / Edit CSV
// extensions, or Excel) + a Markdown table (renders natively in VS Code's
// Markdown preview — Ctrl+Shift+V). Re-run after the data changes.
//
//   node tools/export-data.mjs
//
// No dependencies. Output goes to ./data_exports/.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const web = join(root, "ui_kits", "web");
const outDir = join(root, "data_exports");
mkdirSync(outDir, { recursive: true });

// ── load the pure-data .jsx files in a fake `window` (they end with
//    Object.assign(window, {...}); they contain no JSX, so this just runs them).
const win = {};
function runDataFile(file) {
  const code = readFileSync(join(web, file), "utf8");
  // eslint-disable-next-line no-new-func
  new Function("window", code)(win);
}
runDataFile("data.jsx");        // VM_COMPANIES, VM_INDEX, VM_ANALOGUES, …
runDataFile("admin_data.jsx");  // VM_USERS, vmUserProfits, …

// Course seed lives inside a JSX component file — pull just the array literal.
function loadCourses() {
  try {
    const src = readFileSync(join(web, "Learn.jsx"), "utf8");
    const start = src.indexOf("const LEARN_COURSES = [");
    if (start < 0) return [];
    const open = src.indexOf("[", start);
    const end = src.indexOf("\n];", open);
    const literal = src.slice(open, end + 2); // include the closing ]
    // eslint-disable-next-line no-eval
    return eval(literal);
  } catch (e) { console.warn("  (skipped courses:", e.message + ")"); return []; }
}

// ── helpers ────────────────────────────────────────────────────────────────
const isoDate = (d) => (d instanceof Date ? d.toISOString().slice(0, 10) : d);
const esc = (v) => { v = v == null ? "" : String(v); return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v; };
const toCSV = (rows, cols) => [cols.join(","), ...rows.map((r) => cols.map((c) => esc(r[c])).join(","))].join("\n") + "\n";
const mdCell = (v) => String(v == null ? "" : v).replace(/\|/g, "\\|");
const toMD = (rows, cols) =>
  ["| " + cols.join(" | ") + " |", "| " + cols.map(() => "---").join(" | ") + " |",
   ...rows.map((r) => "| " + cols.map((c) => mdCell(r[c])).join(" | ") + " |")].join("\n") + "\n";
const tally = (rows, key) => rows.reduce((m, r) => ((m[r[key]] = (m[r[key]] || 0) + 1), m), {});

// ── USERS (joined with their personal profits) ───────────────────────────────
const userCols = ["id", "name", "email", "plan", "status", "country", "joined", "last_active",
  "courses_enrolled", "lessons_completed", "portfolio_value", "cost_basis", "profit", "profit_pct", "day_pct"];
const users = win.VM_USERS.map((u) => {
  const p = win.vmUserProfits(u);
  return {
    id: u.id, name: u.name, email: u.email, plan: u.plan, status: u.status, country: u.country,
    joined: isoDate(u.joined), last_active: isoDate(u.lastActive),
    courses_enrolled: u.enrolled, lessons_completed: u.lessons,
    portfolio_value: p.value, cost_basis: p.cost, profit: p.profit,
    profit_pct: p.profitPct.toFixed(1), day_pct: p.dayPct.toFixed(2),
  };
});

// ── COMPANIES (scalar fields only) ───────────────────────────────────────────
const companyCols = ["ticker", "name", "sector", "cap", "price", "chg", "dir", "sub", "analogue", "analogueYear", "match"];
const companies = win.VM_COMPANIES.map((c) => Object.fromEntries(companyCols.map((k) => [k, c[k]])));

// ── COURSES (seed catalogue) ─────────────────────────────────────────────────
const courseCols = ["id", "title", "cat", "provider", "level", "format", "length", "tag"];
const courses = loadCourses().map((c) => Object.fromEntries(courseCols.map((k) => [k, c[k]])));

// ── write everything ─────────────────────────────────────────────────────────
const tables = [
  { name: "users", rows: users, cols: userCols },
  { name: "companies", rows: companies, cols: companyCols },
  { name: "courses", rows: courses, cols: courseCols },
];
for (const t of tables) {
  if (!t.rows.length) continue;
  writeFileSync(join(outDir, t.name + ".csv"), toCSV(t.rows, t.cols));
}

// A readable Markdown summary + the users table (renders as columns in VS Code preview).
const planTally = tally(users, "plan"), statusTally = tally(users, "status");
const usersMd = [
  "# Users — data view",
  "",
  `Generated by \`tools/export-data.mjs\` · ${users.length} users.`,
  "",
  "## Summary",
  "",
  "**By plan:** " + Object.entries(planTally).map(([k, v]) => `${k} ${v}`).join(" · "),
  "",
  "**By status:** " + Object.entries(statusTally).map(([k, v]) => `${k} ${v}`).join(" · "),
  "",
  "## All users",
  "",
  toMD(users, userCols),
].join("\n");
writeFileSync(join(outDir, "users.md"), usersMd);

writeFileSync(join(outDir, "README.md"), [
  "# Data exports",
  "",
  "Flat snapshots of the app's mock database, generated from the data files.",
  "Re-run `node tools/export-data.mjs` after the data changes.",
  "",
  "## Files",
  "",
  "- `users.csv` — the 100 users + their personal-profit figures.",
  "- `companies.csv` — the company list.",
  "- `courses.csv` — the Learn seed catalogue.",
  "- `users.md` — the users table as Markdown (preview it for a column view).",
  "",
  "## Viewing as columns in VS Code",
  "",
  "1. **Markdown preview (no extension):** open `users.md`, press **Ctrl+Shift+V**.",
  "2. **Spreadsheet grid:** install the **Edit CSV** extension (`janisdd.vscode-edit-csv`),",
  "   open a `.csv`, then click *Edit as csv* — you get a sortable grid in the editor.",
  "3. **Coloured columns:** the **Rainbow CSV** extension (`mechatroner.rainbow-csv`)",
  "   colourises columns and adds an *Align* command + SQL-like queries.",
  "",
  "(VS Code will offer to install both — they're listed in `.vscode/extensions.json`.)",
  "",
].join("\n"));

console.log("Wrote to data_exports/:");
for (const t of tables) if (t.rows.length) console.log(`  ${t.name}.csv  (${t.rows.length} rows × ${t.cols.length} cols)`);
console.log("  users.md, README.md");
